using System;
using System.Configuration;
using System.Net.Http;
using System.Net.Http.Headers;

namespace WcfToDoService.Services
{
    /// <summary>
    /// Works with Users backend.
    /// </summary>
    public class UserService
    {
        /// <summary>
        /// The service URL.
        /// </summary>
        private readonly string serviceApiUrl = ConfigurationManager.AppSettings["ToDoServiceUrl"];

        /// <summary>
        /// The url for users' creation.
        /// </summary>
        private const string CreateUrl = "Users";

        private readonly HttpClient httpClient;
        
        /// <summary>
        /// Creates the service.
        /// </summary>
        public UserService()
        {
            httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        /// <summary>
        /// Tries to take existing user using id. If fails then creates a new user with autogenerated name.
        /// </summary>
        /// <param name="id">User id.</param>
        /// <returns>The User Id.</returns>
        public int GetOrCreateUser(string id)
        {
            int userId;

            // No user id or it's damaged
            if (!Int32.TryParse(id, out userId))
            {
                userId = CreateUser("Noname: " + Guid.NewGuid());
            }

            return userId;
        }

        /// <summary>
        /// Creates a user.
        /// </summary>
        /// <param name="userName">The user name.</param>
        /// <returns>The User Id.</returns>
        private int CreateUser(string userName)
        {
            var response = httpClient.PostAsJsonAsync(serviceApiUrl + CreateUrl, userName).Result;
            response.EnsureSuccessStatusCode();
            return response.Content.ReadAsAsync<int>().Result;
        }
    }
}